<?php

// Data functions (insert, update, delete, form) for table ARTICLES

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function ARTICLES_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('ARTICLES');
	if(!$arrPerm[1]){
		return false;
	}

	$data['ARTKEY'] = makeSafe($_REQUEST['ARTKEY']);
		if($data['ARTKEY'] == empty_lookup_value){ $data['ARTKEY'] = ''; }
	$data['ARTNAM'] = makeSafe($_REQUEST['ARTNAM']);
		if($data['ARTNAM'] == empty_lookup_value){ $data['ARTNAM'] = ''; }
	$data['ATYNAM'] = makeSafe($_REQUEST['ATYNAM']);
		if($data['ATYNAM'] == empty_lookup_value){ $data['ATYNAM'] = ''; }
	$data['AGRNAM'] = makeSafe($_REQUEST['AGRNAM']);
		if($data['AGRNAM'] == empty_lookup_value){ $data['AGRNAM'] = ''; }
	if($data['ARTKEY'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'ARTKEY': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: ARTICLES_before_insert
	if(function_exists('ARTICLES_before_insert')){
		$args=array();
		if(!ARTICLES_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `ARTICLES` set       `ARTKEY`=' . (($data['ARTKEY'] !== '' && $data['ARTKEY'] !== NULL) ? "'{$data['ARTKEY']}'" : 'NULL') . ', `ARTNAM`=' . (($data['ARTNAM'] !== '' && $data['ARTNAM'] !== NULL) ? "'{$data['ARTNAM']}'" : 'NULL') . ', `ATYNAM`=' . (($data['ATYNAM'] !== '' && $data['ATYNAM'] !== NULL) ? "'{$data['ATYNAM']}'" : 'NULL') . ', `AGRNAM`=' . (($data['AGRNAM'] !== '' && $data['AGRNAM'] !== NULL) ? "'{$data['AGRNAM']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"ARTICLES_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['ARTKEY'];

	// hook: ARTICLES_after_insert
	if(function_exists('ARTICLES_after_insert')){
		$res = sql("select * from `ARTICLES` where `ARTKEY`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!ARTICLES_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='ARTICLES', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function ARTICLES_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('ARTICLES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ARTICLES' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ARTICLES' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: ARTICLES_before_delete
	if(function_exists('ARTICLES_before_delete')){
		$args=array();
		if(!ARTICLES_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `ARTICLES` where `ARTKEY`='$selected_id'", $eo);

	// hook: ARTICLES_after_delete
	if(function_exists('ARTICLES_after_delete')){
		$args=array();
		ARTICLES_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='ARTICLES' and pkValue='$selected_id'", $eo);
}

function ARTICLES_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('ARTICLES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ARTICLES' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ARTICLES' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['ARTKEY'] = makeSafe($_REQUEST['ARTKEY']);
		if($data['ARTKEY'] == empty_lookup_value){ $data['ARTKEY'] = ''; }
	$data['ARTNAM'] = makeSafe($_REQUEST['ARTNAM']);
		if($data['ARTNAM'] == empty_lookup_value){ $data['ARTNAM'] = ''; }
	$data['ATYNAM'] = makeSafe($_REQUEST['ATYNAM']);
		if($data['ATYNAM'] == empty_lookup_value){ $data['ATYNAM'] = ''; }
	$data['AGRNAM'] = makeSafe($_REQUEST['AGRNAM']);
		if($data['AGRNAM'] == empty_lookup_value){ $data['AGRNAM'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: ARTICLES_before_update
	if(function_exists('ARTICLES_before_update')){
		$args=array();
		if(!ARTICLES_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `ARTICLES` set       `ARTKEY`=' . (($data['ARTKEY'] !== '' && $data['ARTKEY'] !== NULL) ? "'{$data['ARTKEY']}'" : 'NULL') . ', `ARTNAM`=' . (($data['ARTNAM'] !== '' && $data['ARTNAM'] !== NULL) ? "'{$data['ARTNAM']}'" : 'NULL') . ', `ATYNAM`=' . (($data['ATYNAM'] !== '' && $data['ATYNAM'] !== NULL) ? "'{$data['ATYNAM']}'" : 'NULL') . ', `AGRNAM`=' . (($data['AGRNAM'] !== '' && $data['AGRNAM'] !== NULL) ? "'{$data['AGRNAM']}'" : 'NULL') . " where `ARTKEY`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="ARTICLES_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['ARTKEY'];

	// hook: ARTICLES_after_update
	if(function_exists('ARTICLES_after_update')){
		$res = sql("SELECT * FROM `ARTICLES` WHERE `ARTKEY`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ARTKEY'];
		$args = array();
		if(!ARTICLES_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['ARTKEY']}' where tableName='ARTICLES' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function ARTICLES_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('ARTICLES');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='ARTICLES' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='ARTICLES' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `ARTICLES` where `ARTKEY`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/ARTICLES_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/ARTICLES_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'ARTICLES details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return ARTICLES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return ARTICLES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return ARTICLES_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ARTKEY').replaceWith('<div class=\"form-control-static\" id=\"ARTKEY\">' + (jQuery('#ARTKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ARTNAM').replaceWith('<div class=\"form-control-static\" id=\"ARTNAM\">' + (jQuery('#ARTNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ATYNAM').replaceWith('<div class=\"form-control-static\" id=\"ATYNAM\">' + (jQuery('#ATYNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#AGRNAM').replaceWith('<div class=\"form-control-static\" id=\"AGRNAM\">' + (jQuery('#AGRNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ARTKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ARTNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ATYNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(AGRNAM)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ARTKEY)%%>', html_attr($row['ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ARTKEY)%%>', urlencode($urow['ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ARTNAM)%%>', html_attr($row['ARTNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ARTNAM)%%>', urlencode($urow['ARTNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ATYNAM)%%>', html_attr($row['ATYNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ATYNAM)%%>', urlencode($urow['ATYNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(AGRNAM)%%>', html_attr($row['AGRNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AGRNAM)%%>', urlencode($urow['AGRNAM']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ARTKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ARTKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ARTNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ARTNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ATYNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ATYNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(AGRNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AGRNAM)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: ARTICLES_dv
	if(function_exists('ARTICLES_dv')){
		$args=array();
		ARTICLES_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>