<?php

// Data functions (insert, update, delete, form) for table FORECASTVALUES

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function FORECASTVALUES_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('FORECASTVALUES');
	if(!$arrPerm[1]){
		return false;
	}

	$data['CLTNAM'] = makeSafe($_REQUEST['CLTNAM']);
		if($data['CLTNAM'] == empty_lookup_value){ $data['CLTNAM'] = ''; }
	$data['FOR_ARTKEY'] = makeSafe($_REQUEST['FOR_ARTKEY']);
		if($data['FOR_ARTKEY'] == empty_lookup_value){ $data['FOR_ARTKEY'] = ''; }
	$data['FOR_GPRKEY'] = makeSafe($_REQUEST['FOR_GPRKEY']);
		if($data['FOR_GPRKEY'] == empty_lookup_value){ $data['FOR_GPRKEY'] = ''; }
	$data['FOR_ADRKEY'] = makeSafe($_REQUEST['FOR_ADRKEY']);
		if($data['FOR_ADRKEY'] == empty_lookup_value){ $data['FOR_ADRKEY'] = ''; }
	$data['FORMEN'] = makeSafe($_REQUEST['FORMEN']);
		if($data['FORMEN'] == empty_lookup_value){ $data['FORMEN'] = ''; }
	$data['FORMON_F'] = makeSafe($_REQUEST['FORMON_F']);
		if($data['FORMON_F'] == empty_lookup_value){ $data['FORMON_F'] = ''; }
	$data['FORJAH_F'] = makeSafe($_REQUEST['FORJAH_F']);
		if($data['FORJAH_F'] == empty_lookup_value){ $data['FORJAH_F'] = ''; }
	$data['KSTNRA'] = makeSafe($_REQUEST['KSTNRA']);
		if($data['KSTNRA'] == empty_lookup_value){ $data['KSTNRA'] = ''; }
	if($data['FOR_GPRKEY'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'FOR GPRKEY': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: FORECASTVALUES_before_insert
	if(function_exists('FORECASTVALUES_before_insert')){
		$args=array();
		if(!FORECASTVALUES_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `FORECASTVALUES` set       `CLTNAM`=' . (($data['CLTNAM'] !== '' && $data['CLTNAM'] !== NULL) ? "'{$data['CLTNAM']}'" : 'NULL') . ', `FOR_ARTKEY`=' . (($data['FOR_ARTKEY'] !== '' && $data['FOR_ARTKEY'] !== NULL) ? "'{$data['FOR_ARTKEY']}'" : 'NULL') . ', `FOR_GPRKEY`=' . (($data['FOR_GPRKEY'] !== '' && $data['FOR_GPRKEY'] !== NULL) ? "'{$data['FOR_GPRKEY']}'" : 'NULL') . ', `FOR_ADRKEY`=' . (($data['FOR_ADRKEY'] !== '' && $data['FOR_ADRKEY'] !== NULL) ? "'{$data['FOR_ADRKEY']}'" : 'NULL') . ', `FORMEN`=' . (($data['FORMEN'] !== '' && $data['FORMEN'] !== NULL) ? "'{$data['FORMEN']}'" : 'NULL') . ', `FORMON_F`=' . (($data['FORMON_F'] !== '' && $data['FORMON_F'] !== NULL) ? "'{$data['FORMON_F']}'" : 'NULL') . ', `FORJAH_F`=' . (($data['FORJAH_F'] !== '' && $data['FORJAH_F'] !== NULL) ? "'{$data['FORJAH_F']}'" : 'NULL') . ', `KSTNRA`=' . (($data['KSTNRA'] !== '' && $data['KSTNRA'] !== NULL) ? "'{$data['KSTNRA']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"FORECASTVALUES_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['FOR_GPRKEY'];

	// hook: FORECASTVALUES_after_insert
	if(function_exists('FORECASTVALUES_after_insert')){
		$res = sql("select * from `FORECASTVALUES` where `FOR_GPRKEY`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!FORECASTVALUES_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='FORECASTVALUES', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function FORECASTVALUES_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('FORECASTVALUES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='FORECASTVALUES' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='FORECASTVALUES' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: FORECASTVALUES_before_delete
	if(function_exists('FORECASTVALUES_before_delete')){
		$args=array();
		if(!FORECASTVALUES_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `FORECASTVALUES` where `FOR_GPRKEY`='$selected_id'", $eo);

	// hook: FORECASTVALUES_after_delete
	if(function_exists('FORECASTVALUES_after_delete')){
		$args=array();
		FORECASTVALUES_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='FORECASTVALUES' and pkValue='$selected_id'", $eo);
}

function FORECASTVALUES_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('FORECASTVALUES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='FORECASTVALUES' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='FORECASTVALUES' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['CLTNAM'] = makeSafe($_REQUEST['CLTNAM']);
		if($data['CLTNAM'] == empty_lookup_value){ $data['CLTNAM'] = ''; }
	$data['FOR_ARTKEY'] = makeSafe($_REQUEST['FOR_ARTKEY']);
		if($data['FOR_ARTKEY'] == empty_lookup_value){ $data['FOR_ARTKEY'] = ''; }
	$data['FOR_GPRKEY'] = makeSafe($_REQUEST['FOR_GPRKEY']);
		if($data['FOR_GPRKEY'] == empty_lookup_value){ $data['FOR_GPRKEY'] = ''; }
	$data['FOR_ADRKEY'] = makeSafe($_REQUEST['FOR_ADRKEY']);
		if($data['FOR_ADRKEY'] == empty_lookup_value){ $data['FOR_ADRKEY'] = ''; }
	$data['FORMEN'] = makeSafe($_REQUEST['FORMEN']);
		if($data['FORMEN'] == empty_lookup_value){ $data['FORMEN'] = ''; }
	$data['FORMON_F'] = makeSafe($_REQUEST['FORMON_F']);
		if($data['FORMON_F'] == empty_lookup_value){ $data['FORMON_F'] = ''; }
	$data['FORJAH_F'] = makeSafe($_REQUEST['FORJAH_F']);
		if($data['FORJAH_F'] == empty_lookup_value){ $data['FORJAH_F'] = ''; }
	$data['KSTNRA'] = makeSafe($_REQUEST['KSTNRA']);
		if($data['KSTNRA'] == empty_lookup_value){ $data['KSTNRA'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: FORECASTVALUES_before_update
	if(function_exists('FORECASTVALUES_before_update')){
		$args=array();
		if(!FORECASTVALUES_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `FORECASTVALUES` set       `CLTNAM`=' . (($data['CLTNAM'] !== '' && $data['CLTNAM'] !== NULL) ? "'{$data['CLTNAM']}'" : 'NULL') . ', `FOR_ARTKEY`=' . (($data['FOR_ARTKEY'] !== '' && $data['FOR_ARTKEY'] !== NULL) ? "'{$data['FOR_ARTKEY']}'" : 'NULL') . ', `FOR_GPRKEY`=' . (($data['FOR_GPRKEY'] !== '' && $data['FOR_GPRKEY'] !== NULL) ? "'{$data['FOR_GPRKEY']}'" : 'NULL') . ', `FOR_ADRKEY`=' . (($data['FOR_ADRKEY'] !== '' && $data['FOR_ADRKEY'] !== NULL) ? "'{$data['FOR_ADRKEY']}'" : 'NULL') . ', `FORMEN`=' . (($data['FORMEN'] !== '' && $data['FORMEN'] !== NULL) ? "'{$data['FORMEN']}'" : 'NULL') . ', `FORMON_F`=' . (($data['FORMON_F'] !== '' && $data['FORMON_F'] !== NULL) ? "'{$data['FORMON_F']}'" : 'NULL') . ', `FORJAH_F`=' . (($data['FORJAH_F'] !== '' && $data['FORJAH_F'] !== NULL) ? "'{$data['FORJAH_F']}'" : 'NULL') . ', `KSTNRA`=' . (($data['KSTNRA'] !== '' && $data['KSTNRA'] !== NULL) ? "'{$data['KSTNRA']}'" : 'NULL') . " where `FOR_GPRKEY`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="FORECASTVALUES_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['FOR_GPRKEY'];

	// hook: FORECASTVALUES_after_update
	if(function_exists('FORECASTVALUES_after_update')){
		$res = sql("SELECT * FROM `FORECASTVALUES` WHERE `FOR_GPRKEY`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['FOR_GPRKEY'];
		$args = array();
		if(!FORECASTVALUES_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['FOR_GPRKEY']}' where tableName='FORECASTVALUES' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function FORECASTVALUES_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('FORECASTVALUES');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='FORECASTVALUES' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='FORECASTVALUES' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `FORECASTVALUES` where `FOR_GPRKEY`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/FORECASTVALUES_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/FORECASTVALUES_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'FORECASTVALUES details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return FORECASTVALUES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return FORECASTVALUES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return FORECASTVALUES_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#CLTNAM').replaceWith('<div class=\"form-control-static\" id=\"CLTNAM\">' + (jQuery('#CLTNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FOR_ARTKEY').replaceWith('<div class=\"form-control-static\" id=\"FOR_ARTKEY\">' + (jQuery('#FOR_ARTKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FOR_GPRKEY').replaceWith('<div class=\"form-control-static\" id=\"FOR_GPRKEY\">' + (jQuery('#FOR_GPRKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FOR_ADRKEY').replaceWith('<div class=\"form-control-static\" id=\"FOR_ADRKEY\">' + (jQuery('#FOR_ADRKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FORMEN').replaceWith('<div class=\"form-control-static\" id=\"FORMEN\">' + (jQuery('#FORMEN').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FORMON_F').replaceWith('<div class=\"form-control-static\" id=\"FORMON_F\">' + (jQuery('#FORMON_F').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#FORJAH_F').replaceWith('<div class=\"form-control-static\" id=\"FORJAH_F\">' + (jQuery('#FORJAH_F').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#KSTNRA').replaceWith('<div class=\"form-control-static\" id=\"KSTNRA\">' + (jQuery('#KSTNRA').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(CLTNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FOR_ARTKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FOR_GPRKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FOR_ADRKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FORMEN)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FORMON_F)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FORJAH_F)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(KSTNRA)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(CLTNAM)%%>', html_attr($row['CLTNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CLTNAM)%%>', urlencode($urow['CLTNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_ARTKEY)%%>', html_attr($row['FOR_ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_ARTKEY)%%>', urlencode($urow['FOR_ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_GPRKEY)%%>', html_attr($row['FOR_GPRKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_GPRKEY)%%>', urlencode($urow['FOR_GPRKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_ADRKEY)%%>', html_attr($row['FOR_ADRKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_ADRKEY)%%>', urlencode($urow['FOR_ADRKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORMEN)%%>', html_attr($row['FORMEN']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORMEN)%%>', urlencode($urow['FORMEN']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORMON_F)%%>', html_attr($row['FORMON_F']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORMON_F)%%>', urlencode($urow['FORMON_F']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORJAH_F)%%>', html_attr($row['FORJAH_F']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORJAH_F)%%>', urlencode($urow['FORJAH_F']), $templateCode);
		$templateCode=str_replace('<%%VALUE(KSTNRA)%%>', html_attr($row['KSTNRA']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(KSTNRA)%%>', urlencode($urow['KSTNRA']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(CLTNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CLTNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_ARTKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_ARTKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_GPRKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_GPRKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FOR_ADRKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FOR_ADRKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORMEN)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORMEN)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORMON_F)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORMON_F)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FORJAH_F)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FORJAH_F)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(KSTNRA)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(KSTNRA)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: FORECASTVALUES_dv
	if(function_exists('FORECASTVALUES_dv')){
		$args=array();
		FORECASTVALUES_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>