<?php

// Data functions (insert, update, delete, form) for table INVOICEVALUES

// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

function INVOICEVALUES_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('INVOICEVALUES');
	if(!$arrPerm[1]){
		return false;
	}

	$data['CLTNAM'] = makeSafe($_REQUEST['CLTNAM']);
		if($data['CLTNAM'] == empty_lookup_value){ $data['CLTNAM'] = ''; }
	$data['INV_GPRKEY'] = makeSafe($_REQUEST['INV_GPRKEY']);
		if($data['INV_GPRKEY'] == empty_lookup_value){ $data['INV_GPRKEY'] = ''; }
	$data['INV_GPRNAM'] = makeSafe($_REQUEST['INV_GPRNAM']);
		if($data['INV_GPRNAM'] == empty_lookup_value){ $data['INV_GPRNAM'] = ''; }
	$data['INV_ARTKEY'] = makeSafe($_REQUEST['INV_ARTKEY']);
		if($data['INV_ARTKEY'] == empty_lookup_value){ $data['INV_ARTKEY'] = ''; }
	$data['INV_ARTNAM'] = makeSafe($_REQUEST['INV_ARTNAM']);
		if($data['INV_ARTNAM'] == empty_lookup_value){ $data['INV_ARTNAM'] = ''; }
	$data['INVMEN'] = makeSafe($_REQUEST['INVMEN']);
		if($data['INVMEN'] == empty_lookup_value){ $data['INVMEN'] = ''; }
	$data['INVMON_F'] = makeSafe($_REQUEST['INVMON_F']);
		if($data['INVMON_F'] == empty_lookup_value){ $data['INVMON_F'] = ''; }
	$data['INVJAH_F'] = makeSafe($_REQUEST['INVJAH_F']);
		if($data['INVJAH_F'] == empty_lookup_value){ $data['INVJAH_F'] = ''; }
	if($data['INV_GPRKEY'] == '') {echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'INV GPRKEY': " . $Translation['pkfield empty'] . '</div>'; exit;}


	// hook: INVOICEVALUES_before_insert
	if(function_exists('INVOICEVALUES_before_insert')){
		$args=array();
		if(!INVOICEVALUES_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `INVOICEVALUES` set       `CLTNAM`=' . (($data['CLTNAM'] !== '' && $data['CLTNAM'] !== NULL) ? "'{$data['CLTNAM']}'" : 'NULL') . ', `INV_GPRKEY`=' . (($data['INV_GPRKEY'] !== '' && $data['INV_GPRKEY'] !== NULL) ? "'{$data['INV_GPRKEY']}'" : 'NULL') . ', `INV_GPRNAM`=' . (($data['INV_GPRNAM'] !== '' && $data['INV_GPRNAM'] !== NULL) ? "'{$data['INV_GPRNAM']}'" : 'NULL') . ', `INV_ARTKEY`=' . (($data['INV_ARTKEY'] !== '' && $data['INV_ARTKEY'] !== NULL) ? "'{$data['INV_ARTKEY']}'" : 'NULL') . ', `INV_ARTNAM`=' . (($data['INV_ARTNAM'] !== '' && $data['INV_ARTNAM'] !== NULL) ? "'{$data['INV_ARTNAM']}'" : 'NULL') . ', `INVMEN`=' . (($data['INVMEN'] !== '' && $data['INVMEN'] !== NULL) ? "'{$data['INVMEN']}'" : 'NULL') . ', `INVMON_F`=' . (($data['INVMON_F'] !== '' && $data['INVMON_F'] !== NULL) ? "'{$data['INVMON_F']}'" : 'NULL') . ', `INVJAH_F`=' . (($data['INVJAH_F'] !== '' && $data['INVJAH_F'] !== NULL) ? "'{$data['INVJAH_F']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"INVOICEVALUES_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = $data['INV_GPRKEY'];

	// hook: INVOICEVALUES_after_insert
	if(function_exists('INVOICEVALUES_after_insert')){
		$res = sql("select * from `INVOICEVALUES` where `INV_GPRKEY`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!INVOICEVALUES_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='INVOICEVALUES', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function INVOICEVALUES_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('INVOICEVALUES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='INVOICEVALUES' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='INVOICEVALUES' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: INVOICEVALUES_before_delete
	if(function_exists('INVOICEVALUES_before_delete')){
		$args=array();
		if(!INVOICEVALUES_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `INVOICEVALUES` where `INV_GPRKEY`='$selected_id'", $eo);

	// hook: INVOICEVALUES_after_delete
	if(function_exists('INVOICEVALUES_after_delete')){
		$args=array();
		INVOICEVALUES_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='INVOICEVALUES' and pkValue='$selected_id'", $eo);
}

function INVOICEVALUES_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('INVOICEVALUES');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='INVOICEVALUES' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='INVOICEVALUES' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['CLTNAM'] = makeSafe($_REQUEST['CLTNAM']);
		if($data['CLTNAM'] == empty_lookup_value){ $data['CLTNAM'] = ''; }
	$data['INV_GPRKEY'] = makeSafe($_REQUEST['INV_GPRKEY']);
		if($data['INV_GPRKEY'] == empty_lookup_value){ $data['INV_GPRKEY'] = ''; }
	$data['INV_GPRNAM'] = makeSafe($_REQUEST['INV_GPRNAM']);
		if($data['INV_GPRNAM'] == empty_lookup_value){ $data['INV_GPRNAM'] = ''; }
	$data['INV_ARTKEY'] = makeSafe($_REQUEST['INV_ARTKEY']);
		if($data['INV_ARTKEY'] == empty_lookup_value){ $data['INV_ARTKEY'] = ''; }
	$data['INV_ARTNAM'] = makeSafe($_REQUEST['INV_ARTNAM']);
		if($data['INV_ARTNAM'] == empty_lookup_value){ $data['INV_ARTNAM'] = ''; }
	$data['INVMEN'] = makeSafe($_REQUEST['INVMEN']);
		if($data['INVMEN'] == empty_lookup_value){ $data['INVMEN'] = ''; }
	$data['INVMON_F'] = makeSafe($_REQUEST['INVMON_F']);
		if($data['INVMON_F'] == empty_lookup_value){ $data['INVMON_F'] = ''; }
	$data['INVJAH_F'] = makeSafe($_REQUEST['INVJAH_F']);
		if($data['INVJAH_F'] == empty_lookup_value){ $data['INVJAH_F'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: INVOICEVALUES_before_update
	if(function_exists('INVOICEVALUES_before_update')){
		$args=array();
		if(!INVOICEVALUES_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `INVOICEVALUES` set       `CLTNAM`=' . (($data['CLTNAM'] !== '' && $data['CLTNAM'] !== NULL) ? "'{$data['CLTNAM']}'" : 'NULL') . ', `INV_GPRKEY`=' . (($data['INV_GPRKEY'] !== '' && $data['INV_GPRKEY'] !== NULL) ? "'{$data['INV_GPRKEY']}'" : 'NULL') . ', `INV_GPRNAM`=' . (($data['INV_GPRNAM'] !== '' && $data['INV_GPRNAM'] !== NULL) ? "'{$data['INV_GPRNAM']}'" : 'NULL') . ', `INV_ARTKEY`=' . (($data['INV_ARTKEY'] !== '' && $data['INV_ARTKEY'] !== NULL) ? "'{$data['INV_ARTKEY']}'" : 'NULL') . ', `INV_ARTNAM`=' . (($data['INV_ARTNAM'] !== '' && $data['INV_ARTNAM'] !== NULL) ? "'{$data['INV_ARTNAM']}'" : 'NULL') . ', `INVMEN`=' . (($data['INVMEN'] !== '' && $data['INVMEN'] !== NULL) ? "'{$data['INVMEN']}'" : 'NULL') . ', `INVMON_F`=' . (($data['INVMON_F'] !== '' && $data['INVMON_F'] !== NULL) ? "'{$data['INVMON_F']}'" : 'NULL') . ', `INVJAH_F`=' . (($data['INVJAH_F'] !== '' && $data['INVJAH_F'] !== NULL) ? "'{$data['INVJAH_F']}'" : 'NULL') . " where `INV_GPRKEY`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="INVOICEVALUES_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['INV_GPRKEY'];

	// hook: INVOICEVALUES_after_update
	if(function_exists('INVOICEVALUES_after_update')){
		$res = sql("SELECT * FROM `INVOICEVALUES` WHERE `INV_GPRKEY`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['INV_GPRKEY'];
		$args = array();
		if(!INVOICEVALUES_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."', pkValue='{$data['INV_GPRKEY']}' where tableName='INVOICEVALUES' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function INVOICEVALUES_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('INVOICEVALUES');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='INVOICEVALUES' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='INVOICEVALUES' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `INVOICEVALUES` where `INV_GPRKEY`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found']);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/INVOICEVALUES_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/INVOICEVALUES_templateDV.html');
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'INVOICEVALUES details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return INVOICEVALUES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return INVOICEVALUES_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return INVOICEVALUES_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#CLTNAM').replaceWith('<div class=\"form-control-static\" id=\"CLTNAM\">' + (jQuery('#CLTNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INV_GPRKEY').replaceWith('<div class=\"form-control-static\" id=\"INV_GPRKEY\">' + (jQuery('#INV_GPRKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INV_GPRNAM').replaceWith('<div class=\"form-control-static\" id=\"INV_GPRNAM\">' + (jQuery('#INV_GPRNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INV_ARTKEY').replaceWith('<div class=\"form-control-static\" id=\"INV_ARTKEY\">' + (jQuery('#INV_ARTKEY').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INV_ARTNAM').replaceWith('<div class=\"form-control-static\" id=\"INV_ARTNAM\">' + (jQuery('#INV_ARTNAM').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INVMEN').replaceWith('<div class=\"form-control-static\" id=\"INVMEN\">' + (jQuery('#INVMEN').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INVMON_F').replaceWith('<div class=\"form-control-static\" id=\"INVMON_F\">' + (jQuery('#INVMON_F').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#INVJAH_F').replaceWith('<div class=\"form-control-static\" id=\"INVJAH_F\">' + (jQuery('#INVJAH_F').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(CLTNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INV_GPRKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INV_GPRNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INV_ARTKEY)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INV_ARTNAM)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INVMEN)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INVMON_F)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(INVJAH_F)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(CLTNAM)%%>', html_attr($row['CLTNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CLTNAM)%%>', urlencode($urow['CLTNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_GPRKEY)%%>', html_attr($row['INV_GPRKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_GPRKEY)%%>', urlencode($urow['INV_GPRKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_GPRNAM)%%>', html_attr($row['INV_GPRNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_GPRNAM)%%>', urlencode($urow['INV_GPRNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_ARTKEY)%%>', html_attr($row['INV_ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_ARTKEY)%%>', urlencode($urow['INV_ARTKEY']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_ARTNAM)%%>', html_attr($row['INV_ARTNAM']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_ARTNAM)%%>', urlencode($urow['INV_ARTNAM']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVMEN)%%>', html_attr($row['INVMEN']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVMEN)%%>', urlencode($urow['INVMEN']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVMON_F)%%>', html_attr($row['INVMON_F']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVMON_F)%%>', urlencode($urow['INVMON_F']), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVJAH_F)%%>', html_attr($row['INVJAH_F']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVJAH_F)%%>', urlencode($urow['INVJAH_F']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(CLTNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CLTNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_GPRKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_GPRKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_GPRNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_GPRNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_ARTKEY)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_ARTKEY)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INV_ARTNAM)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INV_ARTNAM)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVMEN)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVMEN)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVMON_F)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVMON_F)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(INVJAH_F)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(INVJAH_F)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: INVOICEVALUES_dv
	if(function_exists('INVOICEVALUES_dv')){
		$args=array();
		INVOICEVALUES_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>